version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pytest coverage
            pip install -e .
      - run:
          command: |
            source venv/bin/activate
            cd tests
            coverage run -m pytest -s -v
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov
workflows:
  test:
    jobs:
      - build_test
