version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            pip install -e .
      - run:
          command: |
            cd tests
            source venv/bin/activate
            pytest -s -v tests/
workflows:
  test:
    jobs:
      - build_test
