version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install numpy
            python setup.py install
            pip install -r requirements.txt
      - run:
          command: |
            pytest -s -v tests/
workflows:
  test:
    jobs:
      - build_test
