version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          command: |
            pip install --upgrade pip
            pip install pytest coverage
            pip install -e .
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
      - run:
          command: |
            coverage run -m pytest -s -v tests
            ./codecov
workflows:
  test:
    jobs:
      - build_test
