version: 2.1
orbs:
   codecov: codecov/codecov@3
jobs:
  build_test:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          command: |
            pip install --upgrade pip
            pip install pytest coverage
            pip install -e .
      - run:
          command: |
            cd tests
            coverage run -m pytest -s -v
      - codecov/upload tests/.coverage
workflows:
  test:
    jobs:
      - build_test
